version: 2.1
jobs:
  build:
    bobby:
      - image: alpine:3.7
    steps:
      - checkout
      - run: echo "Hello World"
  
  sally:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run: echo "Double Trouble"
  workflow:
    version: 2
    bobby_sally:
      jobs:
        - bobby
        -sally
