version: 2.1
jobs:
  bobby:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run: echo "Hello World"
  sally:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run: echo "Double Trouble"
workflows:
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally
